include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Triggr
Triggr_FILES = Tweak.x
Triggr_CFLAGS = -fobjc-arc
Triggr_FRAMEWORKS = UIKit AVFoundation QuartzCore LocalAuthentication IOKit AudioToolbox

include $(THEOS_MAKE_PATH)/tweak.mk
